#!/usr/bin/env python3
import rospy
from  cv_bridge import CvBridge 
import cv2
from std_msgs.msg import Image

def Image_callback(msg):
	bridge = CvBridge()
	cv_image = bridge.imgmsg_to_cv2(msg, desired_encoding='passtrought')
	cv2.imshow('okno', cv_image)
rospy.init_node('camera_viewer')
rospy.Subscriber('/usb_cam/image_raw', Image, Image_callback, queue_size=10)
rospy.spin()
